import { Bricolage_Grotesque } from "next/font/google";
import "./globals.css";
import Header from "@/Header/Header";

export const metadata = {
  title: "Daevnt",
  description: "Generated by create next app",
};

const bricolage = Bricolage_Grotesque({
  subsets: ["latin"],
  weight: "600",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${bricolage.className}`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
